//! [`export_protocol_types`]：把 [`crate::Command`]/[`crate::Frame`]
//! 连同它们递归的全部依赖类型导出成 `.ts` 文件（issue 032 点 2/3）。034：
//! 导出 `Frame`（agent 归属信封）而不再单独导出 `SessionEvent`——`Frame` 是
//! 现在真正的下行 SSE wire 形状，`SessionEvent` 是它内层的 `event` 字段类型，
//! ts-rs 的 `export_all` 会把它当依赖递归导出，`SessionEvent.ts` 照样存在，
//! 不用再单独点名一次。

use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::TS;

use crate::http::PollResponse;
use crate::{Command, Frame};

/// 每个生成文件顶部多加的一行。**不是**替换 ts-rs 自己那行
/// 「Do not edit this file manually」——那行还在，这里是补它没有的后半句：
/// «怎么重新生成»，issue 032 验收原文「生成物带『勿手改』头注释与再生成命令」
/// 靠这一行落实。
const REGEN_BANNER: &str =
    "// issue 032：本文件由 Rust 生成，勿手改。重新生成：cargo run -p agent-server --features ts --example gen_protocol_ts\n\n";

/// 导出 `Command`/`Frame`（连同两者递归的全部依赖类型，含 `SessionEvent`）
/// 到 `dir`。
///
/// `large_int_type` 钉死成 `"number"`——ts-rs 给 `u64`/`u128` 的默认是
/// `bigint`，但 `fixtures.json`（见 [`super::fixtures`]）是普通 JSON，
/// `JSON.parse` 出来的数字永远是 `number`，从没有 `bigint` 字面量这回事。
/// 协议里仅有的几个 `u64` 字段（`turn_id`/`barrier_seq`/`skipped`/
/// `original_bytes`/`kept_bytes`）都是计数，离 `Number.MAX_SAFE_INTEGER`
/// （2^53）远得很——选 `number` 不是偷懒，是配合 fixtures 的 `satisfies`
/// 检查：选 `bigint` 的话 `pnpm typecheck` 在 `fixtures.test.ts` 那一行永远红。
///
/// 用 `Config`（不是 `#[ts(export)]` 生成的自动测试）手动调 `export_all`：
/// 自动测试各开一条、各写各的 `TS_RS_EXPORT_DIR`（默认 `./bindings`），没有
/// 「导出到临时目录再跟 `generated/` 比较」这道工序可插——那道工序只能手写，
/// 手写了就不需要再让每个类型各自背一个 `#[ts(export)]`。
pub fn export_protocol_types(dir: &Path) -> Result<(), ts_rs::ExportError> {
    fs::create_dir_all(dir)?;

    let cfg = ts_rs::Config::new().with_large_int("number").with_out_dir(dir);

    Command::export_all(&cfg)?;
    Frame::export_all(&cfg)?;
    PollResponse::export_all(&cfg)?;

    prepend_regen_banner(dir)
}

/// 给 `dir` 下每个 `.ts` 文件（含子目录——ts-rs 自己把 `JsonValue` 放进
/// `serde_json/` 子目录）前面加一行 [`REGEN_BANNER`]。
fn prepend_regen_banner(dir: &Path) -> Result<(), ts_rs::ExportError> {
    for path in list_ts_files(dir)? {
        let original = fs::read_to_string(&path)?;
        fs::write(&path, format!("{REGEN_BANNER}{original}"))?;
    }
    Ok(())
}

/// 递归列出 `dir` 下全部 `.ts` 文件。
fn list_ts_files(dir: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            out.extend(list_ts_files(&path)?);
        } else if path.extension().is_some_and(|ext| ext == "ts") {
            out.push(path);
        }
    }
    Ok(out)
}
